### ISSUE TITLE
Add docker compose

### ISSUE THREAD

**Issue by Psuedoo** [Psuedoo/LinkHive#33]
Would love to have a docker compose for the project. 

Once docker compose is introduced we could implement the use of [docker profiles ](https://docs.docker.com/compose/profiles/). This would allow us to use this Docker container in development. But for now, I think getting this change out for production use is ideal.

I personally don't care to use Docker for development, but this could make it easier for people to contribute if we have the option.

**Comment by Rajdeep1311** [comment]
I would like to work sir

**Comment by Psuedoo** [comment]
@Rajdeep1311 go for it!

**Comment by Psuedoo** [comment]
Still working on this? @Rajdeep1311

**Comment by Rajdeep1311** [comment]
Yes sir
