### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by Psuedoo** [Psuedoo/LinkHive#5]
We need to dockerize the app. Might even want to create an image for it

Things needed:
- [ ] Dockerfile
- [ ] docker-compose.yml
- [ ] User should only need to run `docker-compose up -d` to run the app

**Comment by shivpateriya** [comment]
Could  you provide me or updates so I can help dockerize this app.

**Comment by Psuedoo** [comment]
@shivpateriya sure. Let me know what you would need from me to help you do this. Will update the issue with some requirements.

**Comment by Psuedoo** [comment]
I also have updated the README with some hopefully helpful steps to run the app locally: https://github.com/Psuedoo/LinkHive#local-development-setup

I know it's not the best instructions. But should be enough to get you started.

**Comment by Psuedoo** [comment]
@shivpateriya are you still planning on doing this?

**Comment by shivpateriya** [comment]
Hi i have create a docker file, I will create pull request.

**Comment by Psuedoo** [comment]
@shivpateriya you have to fork the repo and request to merge your PR upstream. Some more information on doing that can be found here: https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project
